podTemplate(label: 'slave',
            containers: [
                    containerTemplate(name: 'terraform', image: 'jenkins/jnlp-agent-terraform:latest', args: '${computer.jnlpmac} ${computer.name}')
            ]) {

        node('slave') {
            stage('Build') {
                container('terraform') {
                    sh 'init'
                }
            }
        }
    }