## run : " docker-compose up"
## if new is created get token from github
version: "3.4"
services:
  runner:
    image: "shaharco1804/runner"
    environment:
        - GH_RUNNER_TOKEN=AN3SN4MPYC4VRDNSENFS6VTDLAKRY
        - GH_REPOSITORY=https://github.com/shaharco99/Devops
#        - first_run=1  ## hide when first run
    #try to fix destroy terraform
    volumes:
      - ./:/Devops