## run : " docker-compose up -d"
## if new is created get token from github
version: "3.4"
services:
  runner:
    image: "shaharco1804/runner"
    environment:
        - GH_RUNNER_TOKEN=AN3SN4KXJDWGQWIRKWCOEL3DKKRY4
        - GH_REPOSITORY=https://github.com/shaharco99/Devops