## run : " docker-compose up"
## if new is created get token from github
version: "3.4"
services:
  runner:
    image: "shaharco1804/runner"
    environment:
        - GH_RUNNER_TOKEN=AN3SN4O4JUMS7ZUHN2ABQKLDKOVJS
        - GH_REPOSITORY=https://github.com/shaharco99/Devops
        - terraform_action=destroy
#        - first_run=1  ## hide when first run
