FROM ubuntu:14.04
RUN apt update -y && \
apt upgrade -y && \
apt -y install software-properties-common && \
apt -y install apache2 libapache2-mod-fcgid composer && \
a2enmod rewrite actions fcgid alias proxy_fcgi && \
add-apt-repository ppa:ondrej/php && \
apt-get update && \
apt install -y php5.4 php5.4-cli php5.4-fpm php5.4-json php5.4-common php5.4-mysql php5.4-zip php5.4-gd php5.4-mbstring \
php5.4-curl php5.4-xml php-pear php5.4-bcmath
COPY playbooks/roles/app/templates/kala-development.conf /etc/apache2/sites-available/99-cms.conf

ENTRYPOINT service apache2 start && service php5.4-fpm start && bash