version: '3.9'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: veryfunny
  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - '8080:80'
    volumes:
      - ./website:/usr/local/apache2/htdocs
