properties([
githubProjectProperty(displayName: '', projectUrlStr: 'https://github.com/shaharco99/Devops/'),
pipelineTriggers([githubPush()])])
pipeline {
    agent {
      dockerfile {
        dir '/Devops/devops_expert/WorldOfGames'
        filename 'Dockerfile'
      }
    }

    stages {
        stage ('checkout') {
              steps {
                checkout scm
            }
        }
    }
}