properties([
githubProjectProperty(displayName: '', projectUrlStr: 'https://github.com/shaharco99/Devops/'),
parameters([ string(defaultValue: 'http://172.19.0.2:5000/', description: 'URL of docker for scores', name: 'url_score', trim: true)]),
pipelineTriggers([githubPush()])])
pipeline {
agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: docker
            image: shaharco1804/test_for_wog:latest
            command:
            - cat
            tty: true
            volumeMounts:
             - mountPath: /var/run/docker.sock
               name: docker-sock
          volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock
        '''
    }
  }


    stages {
        stage('Build') {
              steps {
                container('docker') {
                  sh 'docker build -t shaharco1804/world_of_game:latest  --pull --no-cache devops_expert/WorldOfGames/'
                }
            }
        }
        stage('Run') {
              steps {
                container('docker') {
                  sh 'cd devops_expert/WorldOfGames && docker run -d shaharco1804/world_of_game:latest'
                }
            }
        }
        stage('Test') {
              steps {
                container('docker') {
                  sh 'cd devops_expert/WorldOfGames/test && python3 e2e.py'
                }
            }
        }
        stage('Finalize') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        app.push("${BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }
    }
}