properties([
githubProjectProperty(displayName: '', projectUrlStr: 'https://github.com/shaharco99/Devops/'),
pipelineTriggers([githubPush()])])
pipeline {
agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: docker
            image: shaharco1804/world_of_game
            command:
            - cat
            tty: true
            volumeMounts:
             - mountPath: /var/run/docker.sock
               name: docker-sock
          volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock
        '''
    }
  }

   environment {
       DOCKER_HUB_REPO = "shaharco1804/score_flask"
       CONTAINER_NAME = "score_flask"
   }

    stages {
        stage('Build') {
              steps {
                container('docker') {
                    sh 'docker build -t $DOCKER_HUB_REPO:latest --pull devops_expert/WorldOfGames/score/'
                }
            }
        }
        stage('Run') {
              steps {
                container('docker') {
                    sh 'docker run --rm -d -p 4444:4444 -p 5900:5900 --name selenium shaharco1804/selenium:latest'
                    sh 'docker run --rm -d -p 5000:5000 --name $CONTAINER_NAME $DOCKER_HUB_REPO'                }
            }
        }
        stage('Test') {
              steps {
                container('docker') {
                    sh 'sleep 5 && pytest devops_expert/WorldOfGames/score/e2e.py'
                    sh 'docker rm -f $CONTAINER_NAME || true'
                    sh 'docker rm -f selenium || true'
                }
            }
        }
        stage('Finalize') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        app.push("${BUILD_NUMBER}")
                        app.push("latest")
                    }
                }
            }
        }
    }
}