
pipeline {
    agent any
// Every ten minutes in the first half of every hour (three times, perhaps at :04, :14, :24)
   triggers {pollSCM '''TZ=Israel
    H(0-59)/10 * * * *'''}
   parameters {choice(name: 'action', choices: ['apply', 'destroy'])}
   tools {terraform 'Terraform'}

    stages {
        stage ('terraform init') {
        withCredentials([
        {
              steps {
                dir('terraform-EC2') {
                    sh ('terraform init')
                }
            }
        }
        stage ('terraform Action') {
        withCredentials([string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AKIAYKD7XMBKPHYR6YUS'),string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'PWwUltJaG9CJmj/+LX4KxT3R6XHKAb0WxnZ7CJDE')]) {
            steps {
                dir('terraform-EC2') {
                    sh ('terraform ${action} -auto-approve')
                }
           }
        }
    }
}