Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/focal64"
	config.vm.network :forwarded_port, guest: 80, host: 8080
	config.vm.network :private_network, ip: "192.168.56.10"
	config.vm.synced_folder ".", "/vagrant", type: "nfs"
	config.vm.define :kala do |override|
		override.vm.hostname = "test-vm" #CHANGE TO YOUR OWN HOSTNAME !
	end

	config.vm.provision "ansible" do |ansible|
		ansible.verbose = 'vv'
# 		ansible.tags = ""
		ansible.inventory_path = "playbooks/hosts"
		ansible.limit = "test-vm" #CHANGE TO YOUR OWN HOSTNAME !
		ansible.playbook = "playbooks/provision-debian.yml"
	end

	# Special settings for VirtualBox machine
	# Play with whatever setting you want
	config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--name", "test"]
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
		vb.customize ["modifyvm", :id, "--memory", 2024]
		vb.customize ["modifyvm", :id, "--cpus", 2]
		vb.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
#		vb.customize ["modifyvm", :id, "--ioapic", "on"]
	end

end
