apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  selector:
    name: airflow
  type: NodePort
  ports:
  - name: foo # Actually, no port is needed.
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: airflow
  labels:
    name: airflow
spec:
  containers:
  - image: puckel/docker-airflow
    name: airflow
